service: sankalpam-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: prod
  timeout: 30
  environment:
    NODE_ENV: ${env:NODE_ENV}
    MONGO_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRE: ${env:JWT_EXPIRE}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    MAIL_USER: ${env:MAIL_USER}
    MAIL_PASS: ${env:MAIL_PASS}

functions:
  api:
    handler: src/server.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
